CREATE DATABASE lib1pern;

CREATE TYPE user_type AS ENUM ('ADMIN', 'EMPLOYEE', 'PATRON');
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type user_type NOT NULL,
    first VARCHAR(120) NOT NULL,
    last VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS books (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode VARCHAR(255) NOT NULL UNIQUE,
    cover VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    authors          TEXT[] NOT NULL,
    description      TEXT,
    subjects         TEXT[] NOT NULL,
    publication_date DATE,
    publisher        TEXT,
    pages            INTEGER,
    genre            TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TYPE loan_status AS ENUM ('AVAILABLE', 'LOANED');
CREATE TABLE IF NOT EXISTS loan_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status          loan_status NOT NULL,
    loaned_date     TIMESTAMP DEFAULT NOW(),
    due_date        TIMESTAMP,
    returned_date   TIMESTAMP,
    patron_id       INTEGER REFERENCES users(id),
    employee_out_id INTEGER REFERENCES users(id),
    employee_in_id  INTEGER REFERENCES users(id),
    book_id         INTEGER NOT NULL REFERENCES books(id),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS library_cards (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  INTEGER NOT NULL UNIQUE REFERENCES users(id),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);




