-- Step 1: Create the new tables
CREATE TABLE IF NOT EXISTS books (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode VARCHAR(255) NOT NULL UNIQUE,
    cover_url VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    publication_date DATE,
    publisher TEXT,
    pages INTEGER,
    genre TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS authors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS book_authors (
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    author_id INTEGER NOT NULL REFERENCES authors(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, author_id)
);

CREATE TABLE IF NOT EXISTS subjects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS book_subjects (
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, subject_id)
);

-- Step 2: Migrate authors data
INSERT INTO authors (name)
SELECT DISTINCT unnest(authors) 
FROM books
WHERE authors IS NOT NULL AND array_length(authors, 1) > 0
ON CONFLICT (name) DO NOTHING;

-- Step 3: Populate book_authors junction table
INSERT INTO book_authors (book_id, author_id)
SELECT b.id, a.id
FROM books b
CROSS JOIN LATERAL unnest(b.authors) AS author_name
JOIN authors a ON a.name = author_name
ON CONFLICT DO NOTHING;

-- Step 4: Migrate subjects data
INSERT INTO subjects (name)
SELECT DISTINCT unnest(subjects)
FROM books
WHERE subjects IS NOT NULL AND array_length(subjects, 1) > 0
ON CONFLICT (name) DO NOTHING;

-- Step 5: Populate book_subjects junction table
INSERT INTO book_subjects (book_id, subject_id)
SELECT b.id, s.id
FROM books b
CROSS JOIN LATERAL unnest(b.subjects) AS subject_name
JOIN subjects s ON s.name = subject_name
ON CONFLICT DO NOTHING;

-- Step 6: Remove old columns from books table
ALTER TABLE books DROP COLUMN authors;
ALTER TABLE books DROP COLUMN subjects;

-- Check authors were extracted
SELECT COUNT(*) FROM authors;

-- Check book_authors relationships
SELECT COUNT(*) FROM book_authors;

-- Check a sample book with its authors
SELECT b.title, array_agg(a.name) as authors
FROM books b
LEFT JOIN book_authors ba ON b.id = ba.book_id
LEFT JOIN authors a ON ba.author_id = a.id
GROUP BY b.id, b.title
LIMIT 5;

-- Rename cover to cover_url
ALTER TABLE books RENAME COLUMN cover TO cover_url;



