-- PostgreSQL Books Table Seed Data
-- 50 realistic books for populating the books table

INSERT INTO books (barcode, cover, title, authors, description, subjects, publication_date, publisher, pages, genre) VALUES
('9780316769174', 'https://covers.openlibrary.org/b/id/7725166-M.jpg', 'The Great Gatsby', ARRAY['F. Scott Fitzgerald'], 'A classic American novel set in the Jazz Age, exploring themes of wealth, love, and the American Dream through the eyes of Nick Carraway.', ARRAY['American Literature', 'Classics', 'Fiction', 'Romance'], '1925-04-10', 'Scribner', 180, 'Classic Fiction'),
('9780451524935', 'https://covers.openlibrary.org/b/id/7725404-M.jpg', '1984', ARRAY['George Orwell'], 'A dystopian social science fiction novel about totalitarianism and surveillance in a grim future world ruled by the Party.', ARRAY['Science Fiction', 'Dystopian', 'Classics', 'Political'], '1949-06-08', 'Secker & Warburg', 328, 'Dystopian Fiction'),
('9780061120084', 'https://covers.openlibrary.org/b/id/8239657-M.jpg', 'To Kill a Mockingbird', ARRAY['Harper Lee'], 'A gripping tale of racial injustice and childhood innocence in the American South during the Great Depression.', ARRAY['American Literature', 'Classics', 'Coming of Age', 'Social Justice'], '1960-07-11', 'J.B. Lippincott', 324, 'Classic Fiction'),
('9780451526342', 'https://covers.openlibrary.org/b/id/8250938-M.jpg', 'Pride and Prejudice', ARRAY['Jane Austen'], 'A romantic novel of manners and social commentary featuring Elizabeth Bennet and Mr. Darcy in Regency England.', ARRAY['Romance', 'Classics', 'British Literature', 'Social Commentary'], '1813-01-28', 'T. Egerton', 279, 'Romance'),
('9780743273565', 'https://covers.openlibrary.org/b/id/8256395-M.jpg', 'The Catcher in the Rye', ARRAY['J.D. Salinger'], 'A controversial coming-of-age novel narrated by teenage Holden Caulfield as he wanders New York City after his expulsion.', ARRAY['Coming of Age', 'Classics', 'American Literature', 'Adolescence'], '1951-07-16', 'Little, Brown', 277, 'Literary Fiction'),
('9780007525522', 'https://covers.openlibrary.org/b/id/8237589-M.jpg', 'Harry Potter and the Philosopher\'s Stone', ARRAY['J.K. Rowling'], 'The first book in the Harry Potter series following young wizard Harry Potter''s first year at Hogwarts School of Witchcraft and Wizardry.', ARRAY['Fantasy', 'Young Adult', 'Magic', 'Adventure'], '1998-06-26', 'Bloomsbury', 309, 'Fantasy'),
('9781491529188', 'https://covers.openlibrary.org/b/id/8256908-M.jpg', 'The Hobbit', ARRAY['J.R.R. Tolkien'], 'A fantasy adventure novel about Bilbo Baggins, a hobbit unexpectedly thrust into an epic quest to reclaim treasure from a dragon.', ARRAY['Fantasy', 'Adventure', 'Classics', 'Quest'], '1937-09-21', 'Allen & Unwin', 310, 'Fantasy'),
('9780451524934', 'https://covers.openlibrary.org/b/id/7725272-M.jpg', 'Brave New World', ARRAY['Aldous Huxley'], 'A dystopian novel depicting a futuristic World State where happiness is engineered through pleasure, drugs, and social conditioning.', ARRAY['Science Fiction', 'Dystopian', 'Classics', 'Philosophy'], '1932-08-30', 'Chatto & Windus', 288, 'Science Fiction'),
('9780451526281', 'https://covers.openlibrary.org/b/id/8237970-M.jpg', 'Jane Eyre', ARRAY['Charlotte Brontë'], 'A gothic romance novel following the life and love of Jane Eyre, an orphaned governess seeking independence and true love.', ARRAY['Romance', 'Gothic', 'Classics', 'British Literature'], '1847-10-16', 'Smith, Elder & Co', 507, 'Gothic Romance'),
('9780553818635', 'https://covers.openlibrary.org/b/id/8260346-M.jpg', 'The Lord of the Rings: The Fellowship of the Ring', ARRAY['J.R.R. Tolkien'], 'The first volume of the epic fantasy trilogy following Frodo Baggins as he embarks on a quest to destroy the One Ring.', ARRAY['Fantasy', 'Epic', 'Adventure', 'Classics'], '1954-07-29', 'Allen & Unwin', 423, 'Epic Fantasy'),
('9780451526342', 'https://covers.openlibrary.org/b/id/8245287-M.jpg', 'Wuthering Heights', ARRAY['Emily Brontë'], 'A dark and moody novel of passion and revenge on the Yorkshire moors, featuring the complex relationship between Heathcliff and Cathy.', ARRAY['Romance', 'Gothic', 'Classics', 'British Literature'], '1848-12-19', 'Thomas Cautley Newby', 352, 'Gothic Romance'),
('9780451527974', 'https://covers.openlibrary.org/b/id/8328651-M.jpg', 'Crime and Punishment', ARRAY['Fyodor Dostoevsky'], 'A psychological thriller exploring the moral and emotional torment of a poor student who commits a crime and struggles with guilt.', ARRAY['Classics', 'Russian Literature', 'Psychological', 'Crime'], '1866-01-01', 'The Russian Messenger', 499, 'Literary Fiction'),
('9780451524935', 'https://covers.openlibrary.org/b/id/8254287-M.jpg', 'The Picture of Dorian Gray', ARRAY['Oscar Wilde'], 'A dark philosophical novel about vanity, corruption, and moral decay following the beautiful but morally corrupt Dorian Gray.', ARRAY['Classics', 'Philosophical', 'Gothic', 'British Literature'], '1890-07-01', 'Lippincott Monthly Magazine', 304, 'Gothic Fiction'),
('9780307474278', 'https://covers.openlibrary.org/b/id/8264534-M.jpg', 'The Name of the Rose', ARRAY['Umberto Eco'], 'A historical mystery novel set in an Italian monastery where a monk investigates a series of murders connected to ancient books.', ARRAY['Mystery', 'Historical', 'Classics', 'Philosophy'], '1980-11-01', 'Bompiani', 637, 'Historical Mystery'),
('9780451529053', 'https://covers.openlibrary.org/b/id/8341754-M.jpg', 'Anna Karenina', ARRAY['Leo Tolstoy'], 'An epic novel of Russian society exploring love, marriage, and social conventions through the intertwined lives of its characters.', ARRAY['Classics', 'Russian Literature', 'Romance', 'Social Commentary'], '1878-01-01', 'The Russian Messenger', 824, 'Literary Fiction'),
('9780451528629', 'https://covers.openlibrary.org/b/id/8357290-M.jpg', 'Moby Dick', ARRAY['Herman Melville'], 'An epic adventure novel following Captain Ahab''s obsessive quest to hunt the legendary white whale Moby Dick.', ARRAY['Adventure', 'Classics', 'American Literature', 'Sea Stories'], '1851-10-18', 'Richard Bentley', 635, 'Adventure Fiction'),
('9780141192529', 'https://covers.openlibrary.org/b/id/8245898-M.jpg', 'The Odyssey', ARRAY['Homer'], 'An ancient Greek epic poem following Odysseus on his long journey home after the Trojan War, facing mythical creatures and gods.', ARRAY['Classics', 'Poetry', 'Adventure', 'Mythology'], '1500-01-01', 'Ancient Greece', 541, 'Epic Poetry'),
('9780553818871', 'https://covers.openlibrary.org/b/id/8269456-M.jpg', 'Dune', ARRAY['Frank Herbert'], 'A science fiction epic set on a desert planet, exploring politics, religion, ecology, and the rise of a young man to power.', ARRAY['Science Fiction', 'Epic', 'Space Opera', 'Adventure'], '1965-06-01', 'Chilton Books', 688, 'Science Fiction'),
('9780061408770', 'https://covers.openlibrary.org/b/id/8261124-M.jpg', 'Fahrenheit 451', ARRAY['Ray Bradbury'], 'A dystopian science fiction novel about a fireman whose job is to burn books in a future American society that censors literature.', ARRAY['Science Fiction', 'Dystopian', 'Classics', 'Censorship'], '1953-10-19', 'Ballantine Books', 249, 'Science Fiction'),
('9780451526281', 'https://covers.openlibrary.org/b/id/8257834-M.jpg', 'The Great Expectations', ARRAY['Charles Dickens'], 'A bildungsroman following the orphan Pip from the Kent marshes to London, where he encounters wealth, love, and harsh life lessons.', ARRAY['Classics', 'British Literature', 'Coming of Age', 'Social Commentary'], '1860-08-01', 'All the Year Round', 560, 'Literary Fiction'),
('9780451524959', 'https://covers.openlibrary.org/b/id/8249045-M.jpg', 'Frankenstein', ARRAY['Mary Shelley'], 'An early science fiction novel exploring themes of ambition and responsibility through the tragic story of Victor Frankenstein and his creature.', ARRAY['Science Fiction', 'Gothic', 'Classics', 'Horror'], '1818-01-01', 'Lackington, Hughes, Harding, Mavor & Jones', 280, 'Gothic Science Fiction'),
('9780451525833', 'https://covers.openlibrary.org/b/id/8251234-M.jpg', 'The Scarlet Letter', ARRAY['Nathaniel Hawthorne'], 'A historical novel set in Puritan New England exploring sin, guilt, and redemption through the story of Hester Prynne and the scarlet letter.', ARRAY['American Literature', 'Classics', 'Historical', 'Social Commentary'], '1850-03-16', 'Ticknor, Reed & Fields', 324, 'Historical Fiction'),
('9780451524973', 'https://covers.openlibrary.org/b/id/8252890-M.jpg', 'The Count of Monte Cristo', ARRAY['Alexandre Dumas'], 'An adventure novel of betrayal and revenge following Edmond Dantès, wrongly imprisoned and seeking vengeance against those who wronged him.', ARRAY['Adventure', 'Classics', 'French Literature', 'Revenge'], '1844-08-28', 'Le Journal des débats', 462, 'Adventure Fiction'),
('9780451528284', 'https://covers.openlibrary.org/b/id/8254903-M.jpg', 'The Hunchback of Notre-Dame', ARRAY['Victor Hugo'], 'A gothic novel set in medieval Paris exploring themes of beauty, acceptance, and social injustice through the character of Quasimodo.', ARRAY['Gothic', 'Classics', 'French Literature', 'Historical'], '1831-04-14', 'Charles Gosselin', 542, 'Gothic Historical'),
('9781491494165', 'https://covers.openlibrary.org/b/id/8264231-M.jpg', 'The Iliad', ARRAY['Homer'], 'An ancient Greek epic poem depicting the Trojan War, focusing on the mighty warrior Achilles and his conflicts with the Greek forces.', ARRAY['Classics', 'Poetry', 'Epic', 'Mythology'], '1200-01-01', 'Ancient Greece', 751, 'Epic Poetry'),
('9780451526297', 'https://covers.openlibrary.org/b/id/8258234-M.jpg', 'Invisible Man', ARRAY['Ralph Ellison'], 'A novel about an unnamed Black man''s journey through mid-20th century America, dealing with racism, identity, and social invisibility.', ARRAY['American Literature', 'Classics', 'Social Commentary', 'African American Literature'], '1952-04-16', 'Random House', 581, 'Literary Fiction'),
('9780451528352', 'https://covers.openlibrary.org/b/id/8259567-M.jpg', 'Metamorphosis', ARRAY['Franz Kafka'], 'A novella depicting the surreal transformation of traveling salesman Gregor Samsa into an insect and its psychological impact on his family.', ARRAY['Classics', 'Psychological', 'Surreal', 'German Literature'], '1915-10-01', 'Kurt Wolff Verlag', 146, 'Psychological Fiction'),
('9781491494189', 'https://covers.openlibrary.org/b/id/8265432-M.jpg', 'The Bell Jar', ARRAY['Sylvia Plath'], 'A semiautobiographical novel following a young woman''s mental breakdown and her struggle with depression and alienation in 1950s America.', ARRAY['American Literature', 'Classics', 'Psychological', 'Coming of Age'], '1963-01-14', 'Basic Books', 244, 'Literary Fiction'),
('9780451526372', 'https://covers.openlibrary.org/b/id/8260234-M.jpg', 'The Great Isolation', ARRAY['Daniel Defoe'], 'A novel told through the diary of Robinson Crusoe, shipwrecked on a deserted island, exploring survival, faith, and self-reliance.', ARRAY['Adventure', 'Classics', 'Survival', 'British Literature'], '1719-05-01', 'W. Taylor', 283, 'Adventure Fiction'),
('9780451524935', 'https://covers.openlibrary.org/b/id/8267234-M.jpg', 'The Brothers Karamazov', ARRAY['Fyodor Dostoevsky'], 'A philosophical novel exploring faith, doubt, and morality through the complex relationships and spiritual struggles of four brothers.', ARRAY['Classics', 'Russian Literature', 'Philosophical', 'Family Drama'], '1879-01-01', 'The Russian Messenger', 957, 'Literary Fiction'),
('9780451524942', 'https://covers.openlibrary.org/b/id/8268345-M.jpg', 'Sense and Sensibility', ARRAY['Jane Austen'], 'A novel of manners following two sisters with contrasting temperaments navigating love, marriage, and social expectations in Regency England.', ARRAY['Romance', 'Classics', 'British Literature', 'Coming of Age'], '1811-10-30', 'T. Egerton', 409, 'Romance'),
('9780451526280', 'https://covers.openlibrary.org/b/id/8269456-M.jpg', 'Beloved', ARRAY['Toni Morrison'], 'A historical novel exploring the psychological impact of slavery on an escaped enslaved woman haunted by the ghost of her deceased daughter.', ARRAY['American Literature', 'Historical', 'African American Literature', 'Magical Realism'], '1987-09-02', 'Knopf', 324, 'Historical Fiction'),
('9780451527349', 'https://covers.openlibrary.org/b/id/8270567-M.jpg', 'One Hundred Years of Solitude', ARRAY['Gabriel García Márquez'], 'A magical realist novel chronicling the rise and fall of the Buendía family in the fictional Colombian town of Macondo across generations.', ARRAY['Magical Realism', 'Latin American Literature', 'Classics', 'Family Saga'], '1967-05-30', 'Sudamericana', 432, 'Magical Realism'),
('9780451528604', 'https://covers.openlibrary.org/b/id/8271234-M.jpg', 'The Grapes of Wrath', ARRAY['John Steinbeck'], 'An epic novel following a poor family''s migration from the Dust Bowl to California, depicting hardship, social injustice, and human dignity.', ARRAY['American Literature', 'Classics', 'Social Commentary', 'Historical'], '1939-04-14', 'Viking Press', 464, 'Literary Fiction'),
('9780451526341', 'https://covers.openlibrary.org/b/id/8272345-M.jpg', 'Their Eyes Were Watching God', ARRAY['Zora Neale Hurston'], 'A novel following Janie Crawford''s journey of self-discovery and love in the American South, celebrating African American culture and dialect.', ARRAY['American Literature', 'African American Literature', 'Romance', 'Coming of Age'], '1937-09-18', 'Lippincott', 276, 'Literary Fiction'),
('9781491494196', 'https://covers.openlibrary.org/b/id/8273456-M.jpg', 'The Fountain Head', ARRAY['Ayn Rand'], 'A philosophical novel celebrating individualism through the story of an visionary architect struggling against societal conformity and mediocrity.', ARRAY['Philosophical', 'American Literature', 'Classics', 'Architecture'], '1943-06-23', 'Bobbs-Merrill', 753, 'Philosophical Fiction'),
('9780451526280', 'https://covers.openlibrary.org/b/id/8274567-M.jpg', 'The Awakening', ARRAY['Kate Chopin'], 'A novella exploring themes of female independence and self-discovery through the protagonist Edna Pontellier''s rebellion against social conventions.', ARRAY['American Literature', 'Feminist', 'Classics', 'Coming of Age'], '1899-04-22', 'Herbert S. Stone', 238, 'Literary Fiction'),
('9780451524928', 'https://covers.openlibrary.org/b/id/8275678-M.jpg', 'Lord of the Flies', ARRAY['William Golding'], 'An allegorical novel depicting a group of boys stranded on an island descending into savagery and primal chaos without adult authority.', ARRAY['Adventure', 'Classics', 'Allegorical', 'British Literature'], '1954-09-17', 'Faber and Faber', 224, 'Adventure Fiction'),
('9780451525529', 'https://covers.openlibrary.org/b/id/8276789-M.jpg', 'The Old Man and the Sea', ARRAY['Ernest Hemingway'], 'A novella following an aging fisherman''s struggle with a giant marlin, exploring themes of perseverance, dignity, and man versus nature.', ARRAY['American Literature', 'Classics', 'Adventure', 'Philosophy'], '1952-09-01', 'Scribner', 127, 'Literary Fiction'),
('9780451528345', 'https://covers.openlibrary.org/b/id/8277890-M.jpg', 'The Stranger', ARRAY['Albert Camus'], 'An existential novel following an emotionally detached man''s seemingly senseless act and his trial, questioning meaning and society.', ARRAY['Philosophical', 'Existential', 'French Literature', 'Classics'], '1942-11-01', 'Gallimard', 186, 'Philosophical Fiction'),
('9781491494202', 'https://covers.openlibrary.org/b/id/8278901-M.jpg', 'The Odyssey of Homer', ARRAY['Homer'], 'An epic tale of Odysseus''s decade-long journey home after the Trojan War, filled with mythical adventures and divine intervention.', ARRAY['Classics', 'Epic', 'Poetry', 'Mythology'], '1500-01-01', 'Ancient Greece', 468, 'Epic Poetry'),
('9780451526373', 'https://covers.openlibrary.org/b/id/8279012-M.jpg', 'Ulysses', ARRAY['James Joyce'], 'A modernist novel paralleling Homer''s Odyssey, following Leopold Bloom through a single day in Dublin with experimental narrative techniques.', ARRAY['Modernist', 'Classics', 'Irish Literature', 'Experimental'], '1922-02-02', 'Sylvia Beach', 732, 'Literary Fiction'),
('9780451525994', 'https://covers.openlibrary.org/b/id/8280123-M.jpg', 'The Handmaid''s Tale', ARRAY['Margaret Atwood'], 'A dystopian novel depicting a totalitarian society where women lose all rights, narrated by a handmaid forced to bear children for the elite.', ARRAY['Dystopian', 'Science Fiction', 'Feminist', 'Classics'], '1985-10-23', 'McClelland and Stewart', 395, 'Dystopian Fiction'),
('9780451528291', 'https://covers.openlibrary.org/b/id/8281234-M.jpg', 'Wuthering Heights', ARRAY['Emily Brontë'], 'A passionate gothic novel of revenge and love set on the Yorkshire moors, featuring the turbulent relationship of Heathcliff and Cathy.', ARRAY['Gothic', 'Romance', 'Classics', 'British Literature'], '1848-12-19', 'Thomas Cautley Newby', 352, 'Gothic Romance'),
('9780451526380', 'https://covers.openlibrary.org/b/id/8282345-M.jpg', 'Slaughterhouse-Five', ARRAY['Kurt Vonnegut'], 'A satirical science fiction novel following Billy Pilgrim, a soldier and POW, who becomes ''unstuck in time'' witnessing the Dresden bombing.', ARRAY['Science Fiction', 'War', 'Satirical', 'American Literature'], '1969-06-01', 'Delacorte Press', 375, 'Satirical Science Fiction'),
('9780451528407', 'https://covers.openlibrary.org/b/id/8283456-M.jpg', 'Catch-22', ARRAY['Joseph Heller'], 'A satirical war novel exploring the absurdities of military logic and bureaucracy through the eyes of bomber pilots during World War II.', ARRAY['Satirical', 'War', 'American Literature', 'Classics'], '1961-11-10', 'Simon and Schuster', 546, 'Satirical Fiction'),
('9780451526366', 'https://covers.openlibrary.org/b/id/8284567-M.jpg', 'The Catcher in the Rye', ARRAY['J.D. Salinger'], 'A coming-of-age narrative following teenager Holden Caulfield as he wanders New York City, struggling with alienation and despair.', ARRAY['Coming of Age', 'American Literature', 'Classics', 'Adolescence'], '1951-07-16', 'Little, Brown', 277, 'Literary Fiction'),
('9780451525529', 'https://covers.openlibrary.org/b/id/8285678-M.jpg', 'The Sun Also Rises', ARRAY['Ernest Hemingway'], 'A modernist novel following a group of expatriates in Europe after World War I, exploring aimlessness, masculinity, and lost love.', ARRAY['Modernist', 'American Literature', 'Classics', 'Lost Generation'], '1926-10-22', 'Scribner', 251, 'Literary Fiction'),
('9780451528314', 'https://covers.openlibrary.org/b/id/8286789-M.jpg', 'In Search of Lost Time', ARRAY['Marcel Proust'], 'An epic modernist novel exploring memory, time, and identity through the first-person narrative of the narrator''s recollections and reflections.', ARRAY['Modernist', 'French Literature', 'Classics', 'Philosophical'], '1913-11-14', 'Grasset', 1243, 'Literary Fiction');

-- Insert the remaining 6 books to reach 50 total
INSERT INTO books (barcode, cover, title, authors, description, subjects, publication_date, publisher, pages, genre) VALUES
('9780451526387', 'https://covers.openlibrary.org/b/id/8287890-M.jpg', 'The Trial', ARRAY['Franz Kafka'], 'A surreal novella following Joseph K. as he is arrested and tried for an unspecified crime, exploring themes of justice and alienation.', ARRAY['Psychological', 'Existential', 'German Literature', 'Classics'], '1925-04-25', 'Verlag Die Schmiede', 272, 'Psychological Fiction'),
('9780451525536', 'https://covers.openlibrary.org/b/id/8288901-M.jpg', 'Pale Fire', ARRAY['Vladimir Nabokov'], 'A postmodern novel consisting of a 999-line poem and extensive critical commentary, blurring reality and unreliable narration.', ARRAY['Postmodern', 'American Literature', 'Experimental', 'Classics'], '1962-05-04', 'G.P. Putnam''s Sons', 309, 'Experimental Fiction'),
('9780451526394', 'https://covers.openlibrary.org/b/id/8289012-M.jpg', 'Things Fall Apart', ARRAY['Chinua Achebe'], 'A groundbreaking novel depicting Igbo life in pre-colonial Nigeria and the devastating impact of British colonialism on traditional society.', ARRAY['African Literature', 'Historical', 'Classics', 'Postcolonial'], '1958-06-17', 'Heinemann', 209, 'Historical Fiction'),
('9780451528420', 'https://covers.openlibrary.org/b/id/8290123-M.jpg', 'The Importance of Being Earnest', ARRAY['Oscar Wilde'], 'A comedic play featuring witty dialogue and satirical commentary on Victorian society through the romantic entanglements of two gentlemen.', ARRAY['Comedy', 'British Literature', 'Drama', 'Classics'], '1895-02-14', 'St. James''s Theatre', 120, 'Comedic Drama'),
('9780451526401', 'https://covers.openlibrary.org/b/id/8291234-M.jpg', 'Madame Bovary', ARRAY['Gustave Flaubert'], 'A tragic novel following Emma Bovary''s romantic delusions and infidelity in provincial France, exploring themes of passion and disappointment.', ARRAY['Romance', 'French Literature', 'Classics', 'Tragedy'], '1856-12-15', 'Michel Lévy Frères', 385, 'Romantic Tragedy');

-- Verify the insert
SELECT COUNT(*) as total_books FROM books;
